// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClhaXX1OOVCJLGjLyieDk-mtJvu-4Vp5g',
    appId: '1:484475965484:android:fb9895edb2c65839fb4189',
    messagingSenderId: '484475965484',
    projectId: 'vicsacs-1bfc1',
    storageBucket: 'vicsacs-1bfc1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQDUOzqmSZ1bPa5Ln9oti8r5N6a65DVA',
    appId: '1:484475965484:web:2c0f4e4110829677fb4189',
    messagingSenderId: '484475965484',
    projectId: 'vicsacs-1bfc1',
    authDomain: 'vicsacs-1bfc1.firebaseapp.com',
    storageBucket: 'vicsacs-1bfc1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ3_CL7XgBcSgsLCfrxnYuEJnvQvqr_x4',
    appId: '1:484475965484:ios:d952e4d5f44bfb1afb4189',
    messagingSenderId: '484475965484',
    projectId: 'vicsacs-1bfc1',
    storageBucket: 'vicsacs-1bfc1.firebasestorage.app',
    androidClientId: '484475965484-0q8kl3sre0cpdj0civ0tc18a2uv99rhn.apps.googleusercontent.com',
    iosClientId: '484475965484-s2kran8ap2mi70k1j3t9sflm01ff0241.apps.googleusercontent.com',
    iosBundleId: 'com.example.aminidriver',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ3_CL7XgBcSgsLCfrxnYuEJnvQvqr_x4',
    appId: '1:484475965484:ios:d952e4d5f44bfb1afb4189',
    messagingSenderId: '484475965484',
    projectId: 'vicsacs-1bfc1',
    storageBucket: 'vicsacs-1bfc1.firebasestorage.app',
    androidClientId: '484475965484-0q8kl3sre0cpdj0civ0tc18a2uv99rhn.apps.googleusercontent.com',
    iosClientId: '484475965484-s2kran8ap2mi70k1j3t9sflm01ff0241.apps.googleusercontent.com',
    iosBundleId: 'com.example.aminidriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJQDUOzqmSZ1bPa5Ln9oti8r5N6a65DVA',
    appId: '1:484475965484:web:2b392a994c3ed3c5fb4189',
    messagingSenderId: '484475965484',
    projectId: 'vicsacs-1bfc1',
    authDomain: 'vicsacs-1bfc1.firebaseapp.com',
    storageBucket: 'vicsacs-1bfc1.firebasestorage.app',
  );

}