name: Build Flutter iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # Set your desired stable version here
          architecture: x64         # Avoid arm64 issue

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign
